// PLEASE DO NOT USE THE FONT WEIGHTS IMPORTING THIS FILE FROM NOW ON WE'RE PASSING THIS THRU STYLED COMPONENTS THEME PROP.

export const fontWeight = {
  light: '300',
  regular: '500',
  medium: '700',
  bold: '800'
}
